#!/usr/bin/env node
const { spawn } = require('child_process')
const { openSync } = require('fs')

let outBackEnd = openSync('./logs/outBackEnd.log', 'a'), errBackEnd = openSync('./logs/errBackEnd.log', 'a')
let outFront = openSync('./logs/outFront.log', 'a'), errFront = openSync('./logs/errFront.log', 'a')

spawn('node', ['src/index.js'], { 
  cwd: './backend',
  stdio: ['ignore', outBackEnd, errBackEnd ],
  detached: true
}).unref()

spawn('yarn', ['start'], {
  cwd: './front',
  stdio: ['ignore', outFront, errFront],
  detached: true
}).unref()
